### ISSUE TITLE
Dynamic refresh checkbox does not appear in some browsers

### ISSUE THREAD

**Issue by pmpfr** [kszilagyi/pipeline-board#3]
Safari Version 11.0 (11604.1.38.1.7)

...or in Firefox!

But it does in e.g. Chrome

**Comment by kszilagyi** [comment]
This is now fixed on master but not released yet. Will keep it open until release.

**Comment by kszilagyi** [comment]
Fixed in [1.2](https://github.com/kszilagyi/pipeline-board/releases/tag/v1.2)
