### ISSUE TITLE
Differentiating between pipeline instances

### ISSUE THREAD

**Issue by DanielMoss** [kszilagyi/pipeline-board#5]
Currently I don't believe it's possible to differentiate between two instances of the same pipeline that are run at the same time.

**Comment by kszilagyi** [comment]
Hi, 

So I've done something, looks relatively good on my test data:
![image](https://user-images.githubusercontent.com/29373148/35247100-0579e762-ffc1-11e7-9e8e-f5aa97080146.png)

It looks okay as long as there is no more than 5 stuff running parallel, after that becomes unreadable. Probably still better than what it used to be. Let me know what you think.

**Comment by kszilagyi** [comment]
This seems to work quite well on real data too, closing
